name: CI - Build, Push Docker & Update Kustomize

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/tu-org/encuestapp
  IMAGE_REPO: tu-org/encuestapp
  MANIFESTS_REPO: tu-org/encuestapp-k8s-cloud
  TARGET_OVERLAY: dev

jobs:
  build-publish-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define image tag
        id: vars
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Clone manifests repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MANIFESTS_REPO }}
          token: ${{ secrets.K8S_REPO_PAT }}
          path: manifests

      - name: Update kustomization.yaml with new image tag
        run: |
          cd manifests/overlays/${{ env.TARGET_OVERLAY }}
          kustomize edit set image $IMAGE_NAME=$IMAGE_NAME:$IMAGE_TAG

      - name: Commit and push changes
        run: |
          cd manifests
          git config user.name "GitHub Actions"
          git config user.email "ci@github.com"
          git commit -am "ci: update image to $IMAGE_TAG"
          git push
