name: CI - Build, Push Docker & Patch Manifests 

on:
  push:
    branches:
      - main  # solo en rama main

env:
  IMAGE_NAME: rociomagnoni/prueba
  MANIFESTS_REPO: RocioMagnoni/prueba-k8s-cloud

jobs:
  build-publish-patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v4

      - name: Obtener mensaje del último commit
        id: commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "mensaje_commit=$COMMIT_MSG" >> $GITHUB_OUTPUT

      - name: Detectar overlay según mensaje del commit
        id: overlay
        run: |
          MSG="${{ steps.commit.outputs.mensaje_commit }}"
          if [[ "$MSG" == *"[deploy-dev]"* ]]; then
            echo "overlay=dev" >> $GITHUB_OUTPUT
          elif [[ "$MSG" == *"[deploy-stg]"* ]]; then
            echo "overlay=stg" >> $GITHUB_OUTPUT
          elif [[ "$MSG" == *"[deploy-prod]"* && "$MSG" == *"[approved]"* ]]; then
            echo "overlay=prod" >> $GITHUB_OUTPUT
          else
            echo "overlay=none" >> $GITHUB_OUTPUT
          fi

      - name: Cancelar si no es un commit de deploy
        if: steps.overlay.outputs.overlay == 'none'
        run: |
          echo "No es un commit de deploy. Abortando workflow."
          exit 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Definir tag de la imagen
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build & Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Clonar repo de manifiestos (infra)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MANIFESTS_REPO }}
          token: ${{ secrets.K8S_REPO_PAT }}
          path: prueba-k8s-cloud

      - name: Parchar el deployment con el nuevo tag
        run: |
          OVERLAY=${{ steps.overlay.outputs.overlay }}
          PATCH_FILE="prueba-k8s-cloud/overlays/$OVERLAY/patch-deployment.yaml"

          echo "Actualizando $PATCH_FILE con tag $IMAGE_TAG"
          sed -i "s|image: .*/prueba:.*|image: $IMAGE_NAME:$IMAGE_TAG|g" "$PATCH_FILE"

      - name: Commit & Push de los manifiestos parchados
        run: |
          cd prueba-k8s-cloud
          git config user.email "ci@github.com"
          git config user.name "GitHub Actions"
          git add overlays/${{ steps.overlay.outputs.overlay }}/patch-deployment.yaml
          git commit -m "ci: patch image tag to $IMAGE_TAG for ${{ steps.overlay.outputs.overlay }}" || echo "Sin cambios para commitear"
          git push

